name: Unit_tests

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'dev'

jobs:
  unit_tests:
    name: Run unit tests on push or MR in branch dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}
      - name: Run unit tests
        run: ./gradlew test --stacktrace

#  android_tests:
#    runs-on: [ macos-latest ]
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Instrumentation Tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          script: ./gradlew connectedAndroidTest
