name: Unit_tests

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'dev'

jobs:
  unit_tests:
  runs-on: ubuntu-latest

  steps:
    - name: Run unit tests on push or MR in branch dev
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with: {java-version: 1.8}
    - name: Run unit tests
      run: ./gradlew test
